### ISSUE TITLE
Open access publication

### ISSUE THREAD

**Issue by alice-i-cecile** [rust-ab/rust-ab#26]
Hi! I'm one of Bevy's core developers, but I have an academic background in complex systems ecology. It's really cool to see this project!

The [conference paper](https://discord.com/channels/691052431525675048/954110964083597394/954112395188523048) looks interesting, and I'd love to read it, but I'm no longer affiliated with an institution.

If you're able to, could you post a PDF or preprint?

**Comment by zioposty** [comment]
Sent paper as the attachment of an e-mail.
